"""Arbiter service layer — FIR drafting, section lookup, citizen Q&A.

Each function retrieves grounding sections from the local corpus (offline) and
then either asks Gemini to compose a polished response (if a key is configured)
or falls back to a deterministic, citation-grounded template. Either way the
output cites real sections from the corpus and never invents law.
"""
from __future__ import annotations

from datetime import datetime

from . import llm, store


# --------------------------------------------------------------- section lookup
def suggest_sections(description: str, k: int = 6) -> dict:
    hits = store.retrieve(description, k=k)
    return {
        "query": description,
        "count": len(hits),
        "sections": hits,
        "llm_used": False,
        "source": "RAG retrieval over IPC / IT Act / CrPC corpus",
    }


# --------------------------------------------------------------- FIR draft
def draft_fir(
    incident: str,
    complainant: str = "",
    accused: str = "",
    location: str = "",
    occurred_at: str = "",
    language: str = "en",
) -> dict:
    sections = store.retrieve(incident, k=5)
    citations = [s["citation"] for s in sections]

    prompt = (
        "Draft a First Information Report (FIR) for the incident below, in the "
        "standard Indian format. Include: (1) a clear factual narrative in the "
        "first person of the complainant, (2) the applicable legal sections from "
        "the list provided (do not add any others), (3) details of complainant, "
        "accused, place and time where given.\n\n"
        f"INCIDENT: {incident}\n"
        f"COMPLAINANT: {complainant or 'Not provided'}\n"
        f"ACCUSED: {accused or 'Unknown'}\n"
        f"PLACE: {location or 'Not provided'}\n"
        f"DATE/TIME OF OCCURRENCE: {occurred_at or 'Not provided'}\n\n"
        "APPLICABLE SECTIONS (use only these):\n"
        + "\n".join(f"- {s['citation']}: {s['title']} — {s['summary']}" for s in sections)
    )

    drafted = llm.generate(prompt, language=language)
    if drafted is None:
        drafted = _fir_template(incident, complainant, accused, location,
                                occurred_at, sections)
        llm_used = False
    else:
        llm_used = True

    return {
        "fir_draft": drafted,
        "applicable_sections": sections,
        "citations": citations,
        "llm_used": llm_used,
        "disclaimer": _DISCLAIMER,
    }


def _fir_template(incident, complainant, accused, location, occurred_at,
                  sections) -> str:
    today = datetime.now().strftime("%Y-%m-%d %H:%M")
    sec_lines = "\n".join(
        f"   - {s['citation']} — {s['title']}" for s in sections
    ) or "   - (no specific section matched; review manually)"
    return f"""FIRST INFORMATION REPORT (DRAFT)
(Generated by CityShield · Arbiter — verify before registration)

Date of report : {today}
Complainant    : {complainant or '__________'}
Accused        : {accused or 'Unknown / to be identified'}
Place of offence: {location or '__________'}
Date/time of offence: {occurred_at or '__________'}

1. BRIEF FACTS OF THE CASE
{incident.strip()}

2. APPLICABLE LEGAL PROVISIONS (suggested)
{sec_lines}

3. PRAYER
It is requested that an FIR be registered under the above sections and that the
matter be investigated as per law.

(Signature of Complainant) ____________________
(Recorded by) ____________________  P.S. ____________________

NOTE: This is an AI-assisted draft based on the described facts and the legal
corpus. The investigating officer must verify the facts and the applicability of
each section before registration."""


# --------------------------------------------------------------- citizen Q&A
def answer_query(question: str, language: str = "en", k: int = 5) -> dict:
    sections = store.retrieve(question, k=k)
    prompt = (
        "Answer the following legal question for a citizen in plain, simple "
        "language. Base your answer ONLY on the legal sections provided and cite "
        "them inline. If the sections don't cover it, say so.\n\n"
        f"QUESTION: {question}\n\n"
        "RELEVANT SECTIONS:\n"
        + "\n".join(f"- {s['citation']}: {s['title']} — {s['summary']}" for s in sections)
    )
    answer = llm.generate(prompt, language=language)
    if answer is None:
        answer = _qa_template(question, sections)
        llm_used = False
    else:
        llm_used = True

    return {
        "question": question,
        "answer": answer,
        "sections": sections,
        "citations": [s["citation"] for s in sections],
        "llm_used": llm_used,
        "language": language,
        "disclaimer": _DISCLAIMER,
    }


def _qa_template(question, sections) -> str:
    if not sections:
        return ("No matching legal provision was found in the corpus for this "
                "question. Please consult an officer or lawyer.")
    lines = [
        "Based on the relevant Indian legal provisions:\n",
    ]
    for s in sections[:3]:
        lines.append(f"• {s['citation']} — {s['title']}: {s['summary']} "
                     f"(Punishment: {s['punishment']})")
    lines.append("\nThese sections appear most relevant to your question. "
                 "For formal advice, consult a lawyer or the investigating officer.")
    return "\n".join(lines)


_DISCLAIMER = (
    "AI-generated for assistance only. Not a substitute for legal advice; an "
    "officer or qualified lawyer must verify all sections and facts."
)
