"""Forensic PDF report generation (ReportLab).

Produces a timestamped evidence report: case header, query details, and a grid
of matched frames with camera id, timestamp, similarity score, and detected
objects — suitable for attaching to an investigation file.
"""
from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    Image as RLImage,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from ..config import get_settings
from ..database import get_conn
from ..core.ingestion import format_timestamp

ACCENT = colors.HexColor("#1e3a5f")


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle("VSTitle", parent=styles["Title"],
                              textColor=ACCENT, fontSize=20))
    styles.add(ParagraphStyle("VSMeta", parent=styles["Normal"],
                              fontSize=9, textColor=colors.HexColor("#444444")))
    styles.add(ParagraphStyle("VSCell", parent=styles["Normal"], fontSize=8))
    return styles


def build_report(
    case_title: str,
    investigator: str,
    query: str,
    query_type: str,
    frame_ids: list[int],
) -> bytes:
    settings = get_settings()
    styles = _styles()
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=1.5 * cm, bottomMargin=1.5 * cm,
        leftMargin=1.5 * cm, rightMargin=1.5 * cm,
        title=case_title,
    )

    story = []
    story.append(Paragraph("VisionScan — CCTV Investigation Report", styles["VSTitle"]))
    story.append(Spacer(1, 6))
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    meta = (
        f"<b>Case:</b> {case_title}<br/>"
        f"<b>Investigator:</b> {investigator or 'N/A'}<br/>"
        f"<b>Query ({query_type}):</b> {query or 'N/A'}<br/>"
        f"<b>Generated:</b> {now}<br/>"
        f"<b>Frames in report:</b> {len(frame_ids)}"
    )
    story.append(Paragraph(meta, styles["VSMeta"]))
    story.append(Spacer(1, 12))

    # Resolve frames (preserve caller-supplied order)
    if frame_ids:
        placeholders = ",".join("?" for _ in frame_ids)
        with get_conn() as conn:
            rows = conn.execute(
                "SELECT f.id AS frame_id, f.timestamp_sec, f.thumbnail_path, "
                "v.camera_id, v.filename "
                "FROM frames f JOIN videos v ON v.id = f.video_id "
                f"WHERE f.id IN ({placeholders})",
                frame_ids,
            ).fetchall()
            by_id = {r["frame_id"]: r for r in rows}

            ordered = [by_id[fid] for fid in frame_ids if fid in by_id]
            cells = []
            row_buffer = []
            for r in ordered:
                img_path = settings.thumbnails_dir / r["thumbnail_path"]
                dets = conn.execute(
                    "SELECT label, COUNT(*) c FROM detections WHERE frame_id = ? "
                    "GROUP BY label ORDER BY c DESC LIMIT 4",
                    (r["frame_id"],),
                ).fetchall()
                det_str = ", ".join(f"{d['label']}({d['c']})" for d in dets) or "—"

                try:
                    img = RLImage(str(img_path), width=7.5 * cm, height=4.2 * cm)
                except Exception:
                    img = Paragraph("[image unavailable]", styles["VSCell"])

                caption = (
                    f"<b>{r['camera_id']}</b> @ {format_timestamp(r['timestamp_sec'])}<br/>"
                    f"Frame #{r['frame_id']} · {r['filename']}<br/>"
                    f"Objects: {det_str}"
                )
                cell = [img, Paragraph(caption, styles["VSCell"])]
                row_buffer.append(cell)
                if len(row_buffer) == 2:
                    cells.append(row_buffer)
                    row_buffer = []
            if row_buffer:
                row_buffer.append("")
                cells.append(row_buffer)

        if cells:
            table = Table(cells, colWidths=[8.5 * cm, 8.5 * cm])
            table.setStyle(TableStyle([
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
                ("LINEBELOW", (0, 0), (-1, -1), 0.3, colors.HexColor("#dddddd")),
            ]))
            story.append(table)

    footer = Paragraph(
        "Generated by VisionScan · Frames are AI-ranked candidates and should be "
        "verified by an investigator before use as evidence.",
        styles["VSMeta"],
    )
    story.append(Spacer(1, 12))
    story.append(footer)

    doc.build(story)
    return buf.getvalue()
