import { chromium } from "playwright";
const BASE = process.env.BASE_URL || "http://localhost:5173";
const browser = await chromium.launch();
const page = await browser.newPage();
const errs = [], perrs = [];
page.on("console", (m) => { if (m.type() === "error") errs.push(m.text()); });
page.on("pageerror", (e) => perrs.push(e.message));
await page.goto(BASE, { waitUntil: "networkidle" });
await page.fill('input[type="email"]', "admin@city.gov");
await page.fill('input[type="password"]', "admin123");
await page.click('button[type="submit"]');
await page.waitForSelector("header", { timeout: 8000 });
await page.waitForTimeout(1500);
await page.click('button:has-text("City Map")');
await page.waitForTimeout(4500);
const txt = (await page.evaluate(() => document.body.innerText)).replace(/\s+/g, " ");
const hasMap = txt.includes("City Map") && (txt.includes("hotspot") || txt.includes("Reports") || txt.includes("Risk"));
await page.screenshot({ path: "../docs/assets/debug/admin_citymap.png", fullPage: true });
console.log(JSON.stringify({ consoleErrors: errs, pageErrors: perrs, mapRendered: hasMap, sample: txt.slice(0, 160) }, null, 2));
await browser.close();
